FROM node:16

WORKDIR /app

COPY . .

EXPOSE 3000

CMD ["yarn","start"]


# Efficent way to dockerized image
# FROM node:16 AS builder

# WORKDIR /app

# COPY . .

# RUN yarn build


# FROM nginx:alpine

# WORKDIR /usr/share/nginx/html

# COPY --from=builder /app/build .

# CMD ["nginx","-g","daemon off;"]
